 
services:
  # FastAPI сервис
  fastapi:
    build: ./
    container_name: fastapi-service
    ports:
      - "8000:8000"
    command: python service/api.py  # Только FastAPI
    volumes:
      - ./service/models:/app/service/models
      - ./configs:/app/configs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Градио интерфейс
  gradio:
    build: ./
    container_name: gradio-ui
    ports:
      - "7860:7860"
    command: python service/gradio_ui.py  # Только Gradio
    depends_on:
      fastapi:
        condition: service_healthy
    environment:
      - API_URL=http://fastapi:8000  # Ссылка на FastAPI в сети docker

networks:
  default:
    driver: bridge